[project]
name = "day20"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.3.4",
    "tqdm>=4.67.1",
]

[tool.pytest.ini_options]
python_files = "*.py"
