[project]
authors = [
    {name = "Nick Doornekamp", email = "nddoornekamp@gmail.com"},
]
name = "setup"
version = "0.1.0"
description = "Setup for AoC"
readme = "README.md"
requires-python = "<4.0,>=3.12"
dependencies = [
    "aocd<1.0,>=0.1",
    "typer<1.0.0,>=0.13.0",
]
