[project]
name = "day23"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.3.4",
]

[tool.pytest.ini_options]
python_files = "*.py"